### PR TITLE
Add support for notify groups/actions/services

### PR DESCRIPTION
**Pull request by mathmaniac43**
Per https://github.com/birdwing/HA_Blueprints/issues/1

### CODE REVIEW

**Comment by birdwing** [comment]
Hey @mathmaniac43 

I had wanted to accomplish this as well when I first wrote the blueprint, but I settled on just the Mobile app selection because that was the one I could make into a select box. I want the blueprint to be easy for anyone to use, especially those that might not be HA power users. The ability to simply select the devices that they want the notification to appear on, with the only prerequisite being installing an app, makes the blueprint easy to use for anyone.

The changes you made would allow the groups to work, but it begs the question: "Why have a separate dropdown for the mobile app?" The mobile app notification services could just as easily be added to the text field that you added and it makes the select input redundant.

### Possible Solution
So, with the goal of keeping the blueprint easy for anyone no matter their skill level I think perhaps a small tweak to your addition here could be to make use of the [Blueprint Input Sections](https://www.home-assistant.io/docs/blueprint/schema/#blueprint-input-sections) added in HA 2024.60.

We could organize things under _collapsed by default_ "advanced" sections.
So power users could have the additional features they need while those that just need the simple stuff can safely ignore it.

This goes in line with some of the enhancements I am looking to make (To do lists making use of the "time" of the task rather than them all going out at the same time).

We could organize the sections like this:

**Time, To-do List, and Mobile App Devices to Notify** - Expanded by Default
- Notification Time
- To-do List
- Mobile App Devices to Notify

**Advanced Notification Options** - Collapsed by Default
- Names of Notify Actions/Services

**When Chore is Completed**
- Actions after completed

What do you think?

**Comment by mathmaniac43** [comment]
That sounds totally reasonable to me! Absolutely agree that the simple case that is pre-filtered should be up front too. I am personally hoping that this is a semi-temporary solution until something more permanent is implemented in HA itself, like exposing the notification group services properly.

Would you like to divvy up the inputs into those named/collapsible sections, or would you like me to?

**Comment by birdwing** [comment]
If you could divvy them up that would be great!
I can then pull it down into my local dev site and merge it into what I am working on.

Truth be told, the only reason all notifications go out at the same time is because I use the Google Task integration, which doesn't pull in datetime for the _due_ variable just the date even if there is a time set

So I am working on the ability to have "all day tasks (without a time)" go out at the "Notification Time" while tasks with a time go out at the time they are due (with a reasonable check every 15 minutes, so not exactly on time). With the ability to just toggle a "all tasks go out at same time" to keep current functionality.

So if you are able to expand the functionality to groups and add those sections it would be a big help to me 👍

**Comment by mathmaniac43** [comment]
I think that will do it! Feel free to adjust specific names and descriptions as you see fit, but I did align it pretty well with your original suggestions.

**Comment by birdwing** [comment]
Looks good!
Updated the README, screenshot and made 1 slight adjustment to the *Standard Options* section description.
I have loaded it on my instance of HA, my existing automations with the blueprint updated without issue.
I will wait to verify that it does still work, looks like it will from the code but I like to verify.

I expect to merge this sometime today or tomorrow 👍

**Comment by mathmaniac43** [comment]
Awesome, thanks! Looks great!

**Pull request merged**
